dist: trusty
language: java
jdk: oraclejdk8
addons:
  firefox: latest-esr
before_install:
  - sudo apt-get install xvfb
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
  - sudo tar -xzf geckodriver-v0.19.0-linux64.tar.gz -C /usr/bin
  - sudo chmod a+x /usr/bin/geckodriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5 # give xvfb some time to start
script: 
  - mvn -P AcceptanceTests install

