dist: trusty
language: java
jdk: oraclejdk8
addons:
  firefox: "45.4.0esr"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - npm install selenium-webdriver@^3.141.59
  - npm install
script: 
  - mvn -P AcceptanceTests install
  - mvn install

